name: clean_coverage
description: A tool to clean up your coverage lcov files. Remove unwanted files from your coverage report using globs
version: 0.0.4
homepage: https://github.com/QuirijnGB/clean-coverage

environment:
  sdk: ">=2.12.0 <4.0.0"

executables:
  clean_coverage:

dependencies:
  glob: ^2.0.0
  args: ^2.0.0
  cli_util: ^0.4.2

dev_dependencies:
  lint: ^2.8.0
